development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: joaquin
  password: password1
  database: myapp_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: joaquin
  password: password1
  database: myapp_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: joaquin
  password: password1
  database: myapp_production
